import { useEffect, useId, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { Check, LoaderCircle, X, ImageOff, AlertCircle } from 'lucide-react';
export function Logo({light=false}:{light?:boolean}) { return <div className={`logo ${light?'light':''}`}><span>찍</span></div> }
export function Avatar({name,url,size=38}:{name:string;url?:string|null;size?:number}) {const [failed,setFailed]=useState<string|null>(null);return <span className="avatar" style={{width:size,height:size}}>{url&&failed!==url?<img src={url} alt={name} onError={()=>setFailed(url)}/>:name.slice(0,1)||'?'}</span>}
export function Spinner({label='불러오는 중이에요'}:{label?:string}) {return <div className="loading" role="status"><LoaderCircle className="spin" size={24} aria-hidden="true"/><span>{label}</span></div>}
export function Empty({title='아직 사진이 없어요',description='우리의 첫 번째 추억을 올려보세요.',action}:{title?:string;description?:string;action?:ReactNode}) {return <div className="empty"><span className="empty-icon"><ImageOff size={32}/></span><h3>{title}</h3><p>{description}</p>{action}</div>}
export function ErrorBox({error,retry}:{error:Error;retry?:()=>void}) {return <div className="error-box" role="alert"><AlertCircle size={18} aria-hidden="true"/><span>{error.message}</span>{retry&&<button type="button" onClick={retry}>다시 시도</button>}</div>}
export function Modal({title,subtitle,children,onClose,wide=false,closeDisabled=false}:{title:string;subtitle?:string;children:ReactNode;onClose:()=>void;wide?:boolean;closeDisabled?:boolean}) {
 const ref=useRef<HTMLDivElement>(null);
 const headingId=useId(),descriptionId=useId();
 const closeRef=useRef(onClose),disabledRef=useRef(closeDisabled);closeRef.current=onClose;disabledRef.current=closeDisabled;
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();const handle=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();if(!disabledRef.current)closeRef.current();}if(e.key==='Tab'){const targets=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href],summary,[tabindex="0"]')||[]).filter(element=>element.getClientRects().length>0);if(!targets.length){e.preventDefault();ref.current?.focus();return;}const first=targets[0],last=targets[targets.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',handle);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',handle);if(previous?.isConnected)previous.focus();}},[]);
 return createPortal(<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!closeDisabled)onClose()}}><div ref={ref} tabIndex={-1} className={`modal ${wide?'wide':''}`} role="dialog" aria-modal="true" aria-labelledby={headingId} aria-describedby={subtitle?descriptionId:undefined}><header className="modal-head"><div><h2 id={headingId}>{title}</h2>{subtitle&&<p id={descriptionId}>{subtitle}</p>}</div><button type="button" className="icon-button" onClick={onClose} disabled={closeDisabled} aria-label="닫기"><X size={21}/></button></header>{children}</div></div>,document.body)
}
export function Checkmark({checked}:{checked:boolean}) {return <span className={`checkmark ${checked?'checked':''}`}>{checked&&<Check size={14}/>}</span>}
